[build]
command = "pip install -r requirements.txt"
publish = "public"

[build.environment]
PYTHON_VERSION = "3.9"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
from = "/*"
to = "/.netlify/functions/streamlit"
status = 200
force = true
